/**
 * screenshot_figures.mjs — Playwright screenshot for ALL figures (1-10)
 *
 * Usage:
 *   node screenshot_figures.mjs                    # all figures, both series
 *   node screenshot_figures.mjs --figures 2 3      # specific figures
 *   node screenshot_figures.mjs --series dpmm      # single series
 *
 * Prerequisites:
 *   1. Subplot PNGs generated by generate_subplots.py (for figs 2-10)
 *   2. Symlink: public/subplots → ../../benchmarks/paper_figures/{series}/subplots
 *   3. Next.js dev server running on localhost:3099
 *
 * Size constraint:
 *   Figures are content-fitted — no forced minimum height.
 *   Width is capped at 17cm (670 CSS px × DPR=3 = 2010 px) and height at 21cm.
 *   The script validates each output and warns if above the maximum.
 */

import { chromium } from "playwright";
import path from "path";
import fs from "fs";

// ── Config ───────────────────────────────────────────────────────────────────

const PORT = 3099;
const BASE = `http://localhost:${PORT}`;
const OUT_BASE = "/home/zeyufu/Desktop/PanODE-LAB/benchmarks/paper_figures";
const DPR = 3;  // deviceScaleFactor for high-res output

// Maximum output size at DPR=3 (17cm × 23cm at 288 DPI = 96×3)
// Figures are content-fitted; these are upper bounds, not minimums.
// Height raised to 23cm to accommodate Topic Fig 3 (9 sweeps × 4 metrics).
const MAX_WIDTH_PX  = 2010;   // 17cm at DPR=3 (670px × 3)
const MAX_HEIGHT_PX = 2622;   // 23cm at DPR=3 (874px × 3)

// Per-figure viewport / element sizing
// Width 730 → 670px content + margins.  Heights set generously
// (we screenshot the element, not the viewport).
const FIGURE_CONFIG = {
  1:  { width: 730, height: 780,  rootId: "figure1-root",   filePrefix: "Fig1_arch" },
  2:  { width: 730, height: 2100, rootId: "figure2-root",   filePrefix: "Fig2_base_ablation" },
  3:  { width: 730, height: 3100, rootId: "figure3-root",   filePrefix: "Fig3_sensitivity" },
  4:  { width: 730, height: 4100, rootId: "figure4-root",   filePrefix: "Fig4_training" },
  5:  { width: 730, height: 1600, rootId: "figure5-root",   filePrefix: "Fig5_crossdataset" },
  6:  { width: 730, height: 3200, rootId: "figure6-root",   filePrefix: "Fig6_biological" },
  7:  { width: 730, height: 2800, rootId: "figure7-root",   filePrefix: "Fig7_correlation" },
  8:  { width: 730, height: 4500, rootId: "figure8-root",   filePrefix: "Fig8_umap" },
  9:  { width: 730, height: 2600, rootId: "figure9-root",   filePrefix: "Fig9_enrichment" },
  10: { width: 730, height: 3000, rootId: "figure10-root",  filePrefix: "Fig10_external" },
};

// ── CLI args parsing ─────────────────────────────────────────────────────────

function parseArgs() {
  const args = process.argv.slice(2);
  let figures = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
  let series = ["dpmm", "topic"];

  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--figures") {
      figures = [];
      while (i + 1 < args.length && !args[i + 1].startsWith("--")) {
        figures.push(parseInt(args[++i]));
      }
    }
    if (args[i] === "--series") {
      series = [];
      while (i + 1 < args.length && !args[i + 1].startsWith("--")) {
        series.push(args[++i]);
      }
    }
  }
  return { figures, series };
}

// ── Screenshot one figure ────────────────────────────────────────────────────

async function screenshotFigure(figNum, seriesName) {
  const cfg = FIGURE_CONFIG[figNum];
  if (!cfg) {
    console.error(`Unknown figure: ${figNum}`);
    return;
  }

  const url = `${BASE}/figure${figNum}/${seriesName}`;
  const outDir = path.join(OUT_BASE, seriesName);
  fs.mkdirSync(outDir, { recursive: true });
  const outPath = path.join(outDir, `${cfg.filePrefix}_${seriesName}.png`);

  const browser = await chromium.launch();
  try {
    const page = await browser.newPage({
      viewport: { width: cfg.width, height: cfg.height },
      deviceScaleFactor: DPR,
    });

    console.log(`  → Loading ${url}`);
    await page.goto(url, { waitUntil: "networkidle" });

    // Wait for images to load (for figs 2-6 that load subplot PNGs)
    if (figNum >= 2) {
      await page.waitForTimeout(3000);
      // Wait for all images to finish loading
      await page.evaluate(() => {
        const images = Array.from(document.querySelectorAll("img"));
        return Promise.all(
          images.map((img) =>
            img.complete
              ? Promise.resolve()
              : new Promise((resolve) => {
                  img.onload = resolve;
                  img.onerror = resolve;
                })
          )
        );
      });
      await page.waitForTimeout(500);
    } else {
      await page.waitForTimeout(2000);
    }

    // Remove Next.js dev indicators / overlays before screenshot
    await page.evaluate(() => {
      document.querySelectorAll('[data-nextjs-toast], [data-nextjs-dialog-overlay], nextjs-portal, [data-next-devtools]').forEach(el => el.remove());
      // Also hide any fixed/sticky positioned dev overlays
      document.querySelectorAll('body > div').forEach(el => {
        const s = window.getComputedStyle(el);
        if ((s.position === 'fixed' || s.position === 'sticky') && el.id !== 'figure1-root') {
          el.style.display = 'none';
        }
      });
    });

    const el = await page.$(`#${cfg.rootId}`);
    if (el) {
      await el.screenshot({ path: outPath, type: "png" });
      console.log(`  ✓ Saved: ${outPath}`);

      // ── Validate composed figure size (max 17×21cm) ──────────────────
      const box = await el.boundingBox();
      if (box) {
        const pxW = Math.round(box.width * DPR);
        const pxH = Math.round(box.height * DPR);
        const cmW = (pxW / (DPR * 96) * 2.54).toFixed(1);
        const cmH = (pxH / (DPR * 96) * 2.54).toFixed(1);
        const wOk = pxW <= MAX_WIDTH_PX;
        const hOk = pxH <= MAX_HEIGHT_PX;
        if (!wOk || !hOk) {
          console.warn(`  ⚠ SIZE WARNING: ${pxW}×${pxH}px (${cmW}×${cmH}cm) — exceeds max 17×21cm (${MAX_WIDTH_PX}×${MAX_HEIGHT_PX}px)`);
        } else {
          console.log(`    Size: ${pxW}×${pxH}px (${cmW}×${cmH}cm) — OK ≤ 17×21cm`);
        }
      }
    } else {
      console.error(`  ✗ #${cfg.rootId} not found for figure${figNum}/${seriesName}`);
    }
  } finally {
    await browser.close();
  }
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const { figures, series } = parseArgs();
  console.log(`Screenshotting figures ${figures.join(",")} for series ${series.join(",")}`);

  for (const s of series) {
    console.log(`\nSeries: ${s}`);
    for (const f of figures) {
      try {
        await screenshotFigure(f, s);
      } catch (e) {
        console.error(`  ✗ Error on figure${f}/${s}: ${e.message}`);
      }
    }
  }
  console.log("\nDone.");
}

main();
